#! /bin/sh

bspc monitor -d I II III IV V VI VII VIII

bspc rule -a Gimp -d ^8 --follow --floating
bspc rule -a Chromium -d ^1

bspc rule -a mplayer -d ^8 --follow --floating

bspc config top_padding 	20
bspc config border_width        2
bspc config window_gap          10
bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true

bspc rule -a scratchpad --sticky
bspc config focused_sticky_border_color #817267

bspc control --put-status

#panel &

