#!/bin/bash

function statusbar {

    function desk() {
    DESKTOP_ID=$(xprop -root _NET_CURRENT_DESKTOP | awk '{print $3}')
    DESKTOP_NAME=$(xprop -root _NET_DESKTOP_NAMES | awk -v var=DESKTOP_ID '{ print $var }' | cut -d \" -f2)

    # case $DESKTOP in
    #     4)  echo "main"
    #         ;;
    #     5)  echo "www"
    #         ;;
    #     6)  echo "irc"
    #         ;;
    #     7)  echo "seven"
    #         ;;
    #     8)  echo "eight"
    #         ;;
    #     *)  echo "error"
    # esac
    echo $DESKTOP_ID
    }

    function clock() {
    time=$(date "+%a %e %b // %H:%M")
    echo $time
    }

    function mem() {
    free=$(free -m | grep buffers | awk '{print $3}' | awk '/[0-9]/')
    echo $free
    }

    function temp() {
    tem=$(acpi -t | grep "Thermal 0" | awk '{print $4}')
    echo $tem
    }

    function sda() {
    dfh=$(dfc | grep "/dev/sda4" | awk '{print $3}')
    # dfg=$(df -h | grep "/home" | awk '{print $5}')
    echo $dfh
    }
    
    function ncc() {
    #mus=$(mpc current)
    mus=$(ncmpcpp --now-playing)
    echo $mus
    }

    function bat() {
        bat=$(battery)
        echo $bat
    }
    
    echo "^fg(#4A6787)Desktop ^fg(#ffffff) $(desk) ^fg(#AAAAAA) ^fg(#287373) | ^fg(#4A6787)ram ^fg(#ffffff) $(mem)M ^fg(#98CBFE) | sda ^fg(#ffffff) $(sda) ^fg(#AAAAAA) ^fg(#2B7694) ^fg(#4A6787) | CPU ^fg(#ffffff) $(temp) °C ^fg(#AAAAAA) ^fg(#4A6787) | BAT ^fg(#ffffff) $(bat) % ^fg(#AAAAAA) ^fg(#4A6787) | now playing: ^fg(#ffffff) $(ncc) ^fg(#395573) ^fg(#AAAAAA) | ^fg(#ffffff) $(clock) ^fg(#AAAAAA)"

}
 while true 
 do
    echo "$(statusbar)"
    sleep 0.5
 done | dzen2 -bg '#272822' -fn 'pragmata-8-' -h 20 -ta r -p -xs 2 -dock &
